import JSZip from "jszip";
import { writeFileSync } from "fs";
import { supabaseAdmin } from "../supabase";
import { ZIP_URL, isDoiEntry, commissionerSlug, extractFullName } from "../adapters/eu";

const NOTES_PATH = "lib/identity/eu-unmatched.md";

interface Commissioner {
	slug: string;
	fullName: string;
}

// The ZIP occasionally carries a superseded resubmission alongside the
// current one (same commissioner, "-EN (1).xml" filename) - both slug to
// the same person, so last-write-wins here is fine; it's the same name either way.
async function fetchCommissioners(): Promise<Commissioner[]> {
	const response = await fetch(ZIP_URL);
	if (!response.ok) throw new Error(`EU DOI ZIP fetch failed: ${response.status} ${response.statusText}`);

	const buffer = await response.arrayBuffer();
	const zip = await JSZip.loadAsync(buffer);

	const bySlug = new Map<string, string>();
	for (const [entryName, entry] of Object.entries(zip.files)) {
		if (entry.dir || !isDoiEntry(entryName)) continue;

		const xml = await entry.async("string");
		const fullName = extractFullName(xml);
		if (!fullName) continue; // form without a readable "Full Name" field - don't guess from the filename

		bySlug.set(commissionerSlug(entryName), fullName);
	}

	return [...bySlug.entries()].map(([slug, fullName]) => ({ slug, fullName }));
}

async function upsertOfficial(commissioner: Commissioner): Promise<string> {
	const { data: existing } = await supabaseAdmin
		.from("officials")
		.select("id")
		.eq("country", "EU")
		.contains("external_ids", { eu_doi_slug: commissioner.slug })
		.maybeSingle();

	if (existing) return existing.id;

	const { data: created, error } = await supabaseAdmin
		.from("officials")
		.insert({
			full_name: commissioner.fullName,
			country: "EU",
			chamber: "Commission",
			external_ids: { eu_doi_slug: commissioner.slug },
		})
		.select("id")
		.single();

	if (error || !created) throw new Error(`Failed to create official ${commissioner.fullName}: ${error?.message}`);
	return created.id;
}

async function seedOfficials(commissioners: Commissioner[]): Promise<void> {
	for (const commissioner of commissioners) await upsertOfficial(commissioner);
}

async function fetchUnmatchedEuSlugs(): Promise<string[]> {
	const slugs = new Set<string>();
	let from = 0;
	const pageSize = 1000;
	while (true) {
		const { data, error } = await supabaseAdmin
			.from("disclosure_events")
			.select("official_external_id")
			.eq("country", "EU")
			.is("official_id", null)
			.range(from, from + pageSize - 1);
		if (error) throw error;
		for (const row of data) if (row.official_external_id) slugs.add(row.official_external_id);
		if (data.length < pageSize) break;
		from += pageSize;
	}
	return [...slugs];
}

async function backfillDisclosureEvents(commissioners: Commissioner[]): Promise<{ matched: number; unmatched: string[] }> {
	const slugToName = new Map(commissioners.map((c) => [c.slug, c.fullName]));
	const slugs = await fetchUnmatchedEuSlugs();

	let matched = 0;
	const unmatched: string[] = [];

	for (const slug of slugs) {
		if (!slugToName.has(slug)) {
			unmatched.push(slug);
			continue;
		}

		const { data: official } = await supabaseAdmin
			.from("officials")
			.select("id")
			.eq("country", "EU")
			.contains("external_ids", { eu_doi_slug: slug })
			.maybeSingle();
		if (!official) {
			unmatched.push(slug); // in the current ZIP but the insert above somehow didn't land - flag, don't assume
			continue;
		}

		const { error } = await supabaseAdmin
			.from("disclosure_events")
			.update({ official_id: official.id })
			.eq("country", "EU")
			.eq("official_external_id", slug)
			.is("official_id", null);

		if (error) throw new Error(`Backfill failed for slug ${slug}: ${error.message}`);
		matched++;
	}

	return { matched, unmatched };
}

function writeNotes(unmatched: string[]): void {
	const lines = [
		`# EU officials matching - unresolved cases`,
		``,
		`Generated by \`seed-eu.ts\`. Not committed - see .gitignore.`,
		``,
		`## Unmatched (${unmatched.length})`,
		``,
		...unmatched.map((slug) => `- \`${slug}\` - no match in current Commissioner roster (e.g. a former Commissioner replaced since this disclosure was filed)`),
	];
	writeFileSync(NOTES_PATH, lines.join("\n"));
}

async function main() {
	console.log("Fetching EU Commissioner DOI ZIP...");
	const commissioners = await fetchCommissioners();
	console.log(`${commissioners.length} commissioners found`);

	console.log("Seeding officials...");
	await seedOfficials(commissioners);

	console.log("Backfilling disclosure_events.official_id...");
	const { matched, unmatched } = await backfillDisclosureEvents(commissioners);

	writeNotes(unmatched);
	console.log(`Matched ${matched} unique slugs. ${unmatched.length} unmatched - see ${NOTES_PATH}`);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
