import { writeFileSync } from "fs";
import { supabaseAdmin } from "../supabase";
import { classifyCommittee, type Classification } from "./classify-committee";

const AUDIT_PATH = "lib/committees/committee-sector-relevance-audit.md";
const SECONDARY_WEIGHT = 0.5;

interface CommitteeRow {
	id: string;
	name: string;
	country: string;
	chamber: string;
}

async function fetchAllCommittees(): Promise<CommitteeRow[]> {
	const rows: CommitteeRow[] = [];
	let from = 0;
	const pageSize = 1000;
	while (true) {
		const { data, error } = await supabaseAdmin
			.from("committees")
			.select("id, name, country, chamber")
			.in("country", ["UK", "US"])
			.order("name")
			.range(from, from + pageSize - 1);
		if (error) throw error;
		rows.push(...data);
		if (data.length < pageSize) break;
		from += pageSize;
	}
	return rows;
}

// First sector listed is primary (weight 1), the rest secondary (weight
// 0.5) - not a flat list of equals. No rows inserted for GENERAL/EXCLUDE:
// the ranking formula's coalesce(csr.weight, 0) already treats an absent
// row as 0, so an explicit 0 row would be redundant table bloat (up to
// 328 x 11 rows) for zero behavioural difference - the audit file below is
// the actual record of "considered and rejected" vs "not yet reviewed".
async function seedRelevanceRows(committeeId: string, classification: Extract<Classification, { kind: "sectors" }>): Promise<void> {
	for (const [index, sector] of classification.sectors.entries()) {
		const weight = index === 0 ? 1 : SECONDARY_WEIGHT;
		const { error } = await supabaseAdmin
			.from("committee_sector_relevance")
			.upsert({ committee_id: committeeId, sector, weight }, { onConflict: "committee_id,sector" });
		if (error) throw new Error(`Failed to seed relevance for committee ${committeeId} / ${sector}: ${error.message}`);
	}
}

function describeClassification(classification: Classification): string {
	if (classification.kind === "sectors") {
		const parts = classification.sectors.map((s, i) => `${s}: ${i === 0 ? 1 : SECONDARY_WEIGHT}`);
		return ` - [${parts.join(", ")}] (${classification.reason})`;
	}
	return ` - ${classification.reason}`;
}

function writeAudit(entries: { committee: CommitteeRow; classification: Classification | null }[]): void {
	const bySectors = entries.filter((e) => e.classification?.kind === "sectors");
	const general = entries.filter((e) => e.classification?.kind === "general");
	const excluded = entries.filter((e) => e.classification?.kind === "exclude");
	const unclassified = entries.filter((e) => e.classification === null);

	const section = (title: string, rows: typeof entries) => [
		`## ${title} (${rows.length})`,
		``,
		...rows.map(
			(e) => `- \`[${e.committee.country}/${e.committee.chamber}]\` ${e.committee.name}${e.classification ? describeClassification(e.classification) : ""}`,
		),
		``,
	];

	const lines = [
		`# committee_sector_relevance seeding audit`,
		``,
		"Generated by `seed-committee-sector-relevance.ts`. Every committee's classification and reasoning, for review - not just the unmatched ones, since sector classification is editorial judgment throughout, not a factual lookup. Not committed - see .gitignore.",
		``,
		...section("Classified into sectors", bySectors),
		...section("General jurisdiction (no rows seeded - broad, not sector-specific)", general),
		...section("Excluded (no rows seeded - no real sector jurisdiction)", excluded),
		...section("Unclassified - no rule matched, needs a manual rule added", unclassified),
	];

	writeFileSync(AUDIT_PATH, lines.join("\n"));
}

async function main() {
	console.log("Fetching UK + US committees...");
	const committees = await fetchAllCommittees();
	console.log(`${committees.length} committees found`);

	const entries: { committee: CommitteeRow; classification: Classification | null }[] = [];
	let sectorRowCount = 0;

	for (const committee of committees) {
		const classification = classifyCommittee(committee.name);
		entries.push({ committee, classification });

		if (classification?.kind === "sectors") {
			await seedRelevanceRows(committee.id, classification);
			sectorRowCount += classification.sectors.length;
		}
	}

	writeAudit(entries);

	const sectorsCount = entries.filter((e) => e.classification?.kind === "sectors").length;
	const generalCount = entries.filter((e) => e.classification?.kind === "general").length;
	const excludeCount = entries.filter((e) => e.classification?.kind === "exclude").length;
	const unclassifiedCount = entries.filter((e) => e.classification === null).length;

	console.log(
		`${sectorsCount} committees classified into sectors (${sectorRowCount} relevance rows), ` +
			`${generalCount} general, ${excludeCount} excluded, ${unclassifiedCount} unclassified - see ${AUDIT_PATH}`,
	);
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
